version: '3.3'

services:
  postgres:
    image: postgres
    ports:
    - 5432:5432
    volumes:
    - ./init.sql:/schema_data.sql
    environment:
       POSTGRES_USER: postgres
       POSTGRES_DB: postgres